### ISSUE TITLE
Getting stuck at "INFO - Login via password"

### ISSUE THREAD

**Issue by jakobkilian** [hibobmaster/matrix-stt-bot#1]
Hi! Thanks for providing this repo. Very cool idea that I would like to experiment with for deaf people.

 I am using the Yunohost package [synapse_ynh](https://github.com/YunoHost-Apps/synapse_ynh). I followed the instructions and edited the config.json according to my server dates. Unfortunately when starting the the docker image with `sudo docker compose up` this is the output (won't change in 1 hour):

```
[+] Running 1/0
 ✔ Container matrix-stt-bot  Created                                                                                                                                0.0s 
Attaching to matrix-stt-bot
matrix-stt-bot  | 2023-07-19 18:15:05,645 - INFO - Bot started!
matrix-stt-bot  | 2023-07-19 18:15:11,946 - INFO - Login via password
```

I restarted the system and double checked the login credentials. Using [Cinny](https://github.com/cinnyapp/cinny) I can login just fine. 

This is my current config.json

```
{
    "homeserver": "https://matrix.MYDOMAIN.de",
    "user_id": "@botwhisper:MYDOMAIN.de",
    "password": "************",
    "device_id": "GMIAZSVFF",
    "room_id": "!mDqFzeYMAuCTDOlrBh:MYDOMAIN.de",
    "model_size": "medium",
    "import_keys_path": "element-keys.txt",
    "import_keys_password": "************"
}
```

Any idea? How can I get more verbose logging on why the login doesn't work?

**Comment by hibobmaster** [comment]
I just tested it without problem, It seems you stuck at model downloading step. Can you provide your working directory screenshot for me?
Besides, you can try without importing e2ee keys, here is my test configuration.
`config.json`
```json
{
    "homeserver": "https://xxxxx.xxx",
    "user_id": "@lullap:xxx.xxxx",
    "password": "xxxxxxxxxx@NABYGaS^9",
    "device_id": "DFYEOKVPLG",
    "room_id": "!pgFjjtPUiAXSMyTmTU:matrix.qqs.tw",
    "model_size": "base"
}
```
`compose.yaml`
```yaml
services:
  app:
    image: ghcr.io/hibobmaster/matrix-stt-bot:latest
    container_name: matrix-stt-bot
    restart: always
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # env_file:
    #   - .env
    volumes:
      # use env file or config.json
      - ./config.json:/app/config.json
      # use touch to create an empty file stt_db, for persist database only
      - ./stt_db:/app/db
      # import_keys path
      # - ./element-keys.txt:/app/element-keys.txt
      # store whisper models that program will download
      - ./models:/app/models
    networks:
      - matrix_network

networks:
  matrix_network:
```

Some errors can be ignored if you are not using E2EE room.

![image](https://github.com/hibobmaster/matrix-stt-bot/assets/32976627/b9aba592-e7fa-4b4d-9d3b-09fd8b92f574)
![image](https://github.com/hibobmaster/matrix-stt-bot/assets/32976627/edaa507f-5109-4151-b1ad-4abc825fda40)
![image](https://github.com/hibobmaster/matrix-stt-bot/assets/32976627/dec8bb1b-4a2d-48f0-92c7-11f79526ab34)
